# Generated by Django 2.1.4 on 2018-12-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_serie', models.CharField(max_length=60)),
                ('title', models.TextField(blank=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('periodicity', models.CharField(blank=True, max_length=100)),
                ('figure', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
