# Generated by Django 2.1.4 on 2018-12-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumplo_test_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='figures/')),
            ],
        ),
    ]
